baseURL = "https://zzkrix.com/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "é¿é£æ¸¯"
theme = "DoIt"

[menu]
[[menu.main]]
identifier = "posts"
# ä½ å¯ä»¥åœ¨åç§° ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰ ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯ï¼Œä¾‹å¦‚å›¾æ ‡
pre = ""
# ä½ å¯ä»¥åœ¨åç§° ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰ ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯ï¼Œä¾‹å¦‚å›¾æ ‡
post = ""
name = "æ–‡ç« "
url = "/posts/"
# å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶ï¼Œå°†æ˜¾ç¤ºçš„æ ‡é¢˜
title = ""
weight = 1
[[menu.main]]
identifier = "life"
pre = ""
post = ""
name = "ç”Ÿæ´»"
url = "/life/"
title = ""
weight = 2
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "æ ‡ç­¾"
url = "/tags/"
title = ""
weight = 3
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "åˆ†ç±»"
url = "/categories/"
title = ""
weight = 4
[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "å…³äº"
url = "/about/"
title = ""
weight = 5

[params]
#  DoIt ä¸»é¢˜ç‰ˆæœ¬
version = "0.4.X"
# ç½‘ç«™åç§°
title = "é¿é£æ¸¯"
# ç½‘ç«™æè¿°
description = "xxx"
# ç½‘ç«™å…³é”®è¯
keywords = ["Theme", "Hugo"]
#  ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ("light", "dark", "black", "auto")
defaultTheme = "auto"
# å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
gitRepo = ""
#  å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
#  æ—¥æœŸæ ¼å¼
dateFormat = "2006-01-02"
# ç½‘ç«™å›¾ç‰‡ï¼Œç”¨äº Open Graph å’Œ Twitter Cards
images = ["/logo.png"]
#  å¼€å¯ PWA æ”¯æŒ
enablePWA = false
# ã€è¯•éªŒæ€§åŠŸèƒ½ã€‘ ç¼“å­˜ markdown ä¸­çš„å›¾ç‰‡é“¾æ¥åˆ°æœ¬åœ°ï¼Œè¯¦æƒ…è¯·è§ï¼šhttps://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
cacheRemoteImages = false
# ã€è¯•éªŒæ€§åŠŸèƒ½ã€‘ ä½¿ç”¨ hugo è‡ªå¸¦çš„å›¾ç‰‡å¤„ç†åŠŸèƒ½ç”Ÿæˆ srcset å±æ€§
optimizeImages = true
# ã€å®éªŒæ€§åŠŸèƒ½ã€‘ optimizeImages ä¸­ srcset å±æ€§çš„ç¼©æ”¾æ–¹æ³•ï¼Œè¯¦æƒ…è¯·è§ï¼šhttps://gohugo.io/content-management/image-processing/#image-processing-options
srcsetSmallResizeMethod = "700x webp Lanczos q75"
srcsetDefaultResizeMethod = "1200x webp Lanczos q75"
srcsetLargeResizeMethod = "2000x webp Lanczos q75"
#  ç‰ˆæƒä¿¡æ¯
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# ä½œè€…é…ç½®
[params.author]
name = "zzkrix"
email = "zzkrix56@gmail.com"
link = "https://zzkrix.com"
avatar = ""
gravatarEmail = ""
#  åº”ç”¨å›¾æ ‡é…ç½®
[params.app]
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜ï¼Œè¦†ç›–é»˜è®¤æ ‡é¢˜
title = "DoIt"
# æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
noFavicon = false
# æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡ï¼Œå¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
svgFavicon = ""
# Safari å›¾æ ‡é¢œè‰²
iconColor = "#5bbad5"
# Windows v8-10 ç£è´´é¢œè‰²
tileColor = "#da532c"

#  æœç´¢é…ç½®
[params.search]
enable = true
# æœç´¢å¼•æ“çš„ç±»å‹ ("algolia", "fuse")
type = "fuse"
# æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
contentLength = 4000
# æœç´¢æ¡†çš„å ä½æç¤ºè¯­
placeholder = ""
#  æœ€å¤§ç»“æœæ•°ç›®
maxResultLength = 10
#  ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
snippetLength = 50
#  æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
highlightTag = "em"
#  æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
absoluteURL = false
[params.search.algolia]
index = ""
appID = ""
searchKey = ""
[params.search.fuse]
#  https://fusejs.io/api/options.html
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[params.image]
# ç¼“å­˜å›¾ç‰‡é“¾æ¥åˆ°æœ¬åœ°
cacheRemote = false
# å›¾ç‰‡ç¼©æ”¾å’Œä¼˜åŒ–
optimise = true
# é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
[params.header]
#  ä¸»é¢˜åˆ‡æ¢æ¨¡å¼
# ä¸»é¢˜åˆ‡æ¢æ¨¡å¼ ("switch", "select")
themeChangeMode = "switch"
#  é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
[params.header.title]
# LOGO çš„ URL
logo = "https://avatars.githubusercontent.com/u/173884861?v=4"
# æ ‡é¢˜åç§°
name = "è¡Œè€…å¸¸è‡³ï¼Œä¸ºè€…å¸¸æˆï½"
# ä½ å¯ä»¥åœ¨åç§° ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰ ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯ï¼Œä¾‹å¦‚å›¾æ ‡
pre = "ğŸ’¥"
# ä½ å¯ä»¥åœ¨åç§° ï¼ˆå…è®¸ HTML æ ¼å¼ï¼‰ ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯ï¼Œä¾‹å¦‚å›¾æ ‡
post = ""
#  æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true

# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[params.footer]
enable = true
#  è‡ªå®šä¹‰å†…å®¹ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
custom = ''
#  æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
hugo = true
#  æ‰˜ç®¡æœåŠ¡ä¿¡æ¯ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
# <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>
hostedOn = ''
#  æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
copyright = true
#  æ˜¯å¦æ˜¾ç¤ºä½œè€…
author = true
# ç½‘ç«™åˆ›ç«‹å¹´ä»½
since = 1900
# ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
icp = "non-ICP"
# è®¸å¯åè®®ä¿¡æ¯ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section ï¼ˆæ‰€æœ‰æ–‡ç« ï¼‰ é¡µé¢é…ç½®
[params.section]
# section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
# æ—¥æœŸæ ¼å¼ ï¼ˆæœˆå’Œæ—¥ï¼‰
dateFormat = "01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 10
#  æœ€è¿‘æ›´æ–°æ–‡ç« è®¾ç½®
[params.section.recentlyUpdated]
enable = false
rss = false
days = 30
maxCount = 10

#  List ï¼ˆç›®å½•æˆ–æ ‡ç­¾ï¼‰ é¡µé¢é…ç½®
[params.list]
# list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 20
# æ—¥æœŸæ ¼å¼ ï¼ˆæœˆå’Œæ—¥ï¼‰
dateFormat = "01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 20

# ä¸»é¡µé…ç½®
[params.home]
#  RSS æ–‡ç« æ•°ç›®
rss = 20
# ä¸»é¡µä¸ªäººä¿¡æ¯
[params.home.profile]
enable = true
# Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
gravatarEmail = ""
# ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
# å°†ä½ çš„å¤´åƒæ–‡ä»¶æ”¾ç½®äº static æˆ–è€… assets ç›®å½•ä¸‹
# æ–‡ä»¶è·¯å¾„æ˜¯ç›¸å¯¹äº static æˆ–è€… assets ç›®å½•çš„
# avatarURL = "/images/avatar.webp"
avatarURL = ""
# å¤´åƒçš„é“¾æ¥æŒ‡å‘çš„ URL
avatarLinkURL = ""
#  ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
#title = '<div style="text-align: center;"><p style="margin-bottom: 10px; font-size: 20px; font-weight: bold;">Hello World</p><img src="https://raw.githubusercontent.com/zzkrix/blog-images/main/assets/2024-01-22-14-51-MgyDly.jpg" alt="eureka" style="display: block; margin: 0 auto 20px auto;"><img src="https://raw.githubusercontent.com/zzkrix/blog-images/main/assets/2024-03-22-09-28-lBbSAW.gif" alt="gif" style="display: block; margin: 0 auto;"></div>'
title = '<div style="text-align: center; margin-top: 8vh;"><img src="https://raw.githubusercontent.com/zzkrix/blog-images/main/assets/2024-01-22-14-51-MgyDly.jpg" alt="eureka" style="display: block; margin: 0 auto 20px auto;"><img src="https://raw.githubusercontent.com/zzkrix/blog-images/main/assets/2024-03-22-09-28-lBbSAW.gif" alt="gif" style="display: block; margin: 0 auto;"></div>'

# ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
subtitle = ""
# æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true
# æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
social = false
#  å…è´£å£°æ˜ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
disclaimer = ''
# ä¸»é¡µæ–‡ç« åˆ—è¡¨
[params.home.posts]
enable = false
# ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 10
#  è¢« params.page ä¸­çš„ hiddenFromHomePage æ›¿ä»£
# å½“ä½ æ²¡æœ‰åœ¨æ–‡ç« å‰ç½®å‚æ•°ä¸­è®¾ç½® "hiddenFromHomePage" æ—¶çš„é»˜è®¤è¡Œä¸º
defaultHiddenFromHomePage = false

# ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
[params.social]
GitHub = "zzkrix"
Linkedin = ""
Twitter = ""
Instagram = ""
Facebook = ""
Telegram = ""
Medium = ""
Gitlab = ""
Youtubelegacy = ""
Youtubecustom = ""
Youtubechannel = ""
Tumblr = ""
Quora = ""
Keybase = ""
Pinterest = ""
Reddit = ""
Codepen = ""
FreeCodeCamp = ""
Bitbucket = ""
Stackoverflow = ""
Weibo = ""
Odnoklassniki = ""
VK = ""
Flickr = ""
Xing = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Bandcamp = ""
Paypal = ""
Fivehundredpx = ""
Mix = ""
Goodreads = ""
Lastfm = ""
Foursquare = ""
Hackernews = ""
Kickstarter = ""
Patreon = ""
Steam = ""
Twitch = ""
Strava = ""
Skype = ""
Whatsapp = ""
Zhihu = ""
Douban = ""
Angellist = ""
Slidershare = ""
Jsfiddle = ""
Deviantart = ""
Behance = ""
Dribbble = ""
Wordpress = ""
Vine = ""
Googlescholar = ""
Researchgate = ""
Mastodon = ""
Thingiverse = ""
Devto = ""
Gitea = ""
XMPP = ""
Matrix = ""
Bilibili = ""
ORCID = ""
Liberapay = ""
Ko-Fi = ""
BuyMeACoffee = ""
Linktree = ""
QQ = ""
QQGroup = ""
Email = "zzkrix56@gmail.com"
RSS = true

#  æ–‡ç« é¡µé¢é…ç½®
[params.page]
#  æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromHomePage = false
#  æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromSearch = false
#  æ˜¯å¦ä½¿ç”¨ twemoji
twemoji = false
# æ˜¯å¦ä½¿ç”¨ lightgallery
lightgallery = false
#  æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
ruby = true
#  æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
fraction = true
# æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
linkToMarkdown = true
#  é…ç½®æ–‡ç« åŸå§‹æ–‡ä»¶çš„é“¾æ¥
linkToSource = false
# "https://github.com/user/repo/blob/main/{path}"
#  é…ç½®ç¼–è¾‘æ–‡ç« çš„é“¾æ¥
linkToEdit = false
# "https://github.com/user/repo/edit/main/{path}"
# "https://gitlab.com/user/repo/-/edit/main/{path}"
# "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
#  é…ç½®æäº¤é”™è¯¯çš„é“¾æ¥
linkToReport = false
# "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
#  æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
rssFullText = false
#  æ˜¯å¦åœ¨æ–‡ç« å¼€å¤´æ˜¾ç¤ºç³»åˆ—å¯¼èˆª
seriesNavigation = true
# æ˜¯å¦å¯ç”¨æœ€åä¿®æ”¹æ—¶é—´
enableLastMod = false
# æ˜¯å¦å¯ç”¨å­—æ•°ç»Ÿè®¡
enableWordCount = true
# æ˜¯å¦å¯ç”¨é˜…è¯»æ—¶é—´ä¼°è®¡
enableReadingTime = true
#  è¿‡æ—¶æ–‡ç« æç¤º
[params.page.outdatedArticleReminder]
enable = false
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äº 90 å¤©ä¹‹å‰ï¼Œæ˜¾ç¤ºæé†’
reminder = 90
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äº 180 å¤©ä¹‹å‰ï¼Œæ˜¾ç¤ºè­¦å‘Š
warning = 180
#  ç›®å½•é…ç½®
[params.page.toc]
# æ˜¯å¦ä½¿ç”¨ç›®å½•
enable = true
#  æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
keepStatic = false
# æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
auto = false
#  ä»£ç é…ç½®
[params.page.code]
# é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
maxShownLines = 999
# æ˜¯å¦æ˜¾ç¤ºä»£ç è¡Œå·
lineNos = true
# æ˜¯å¦å¼€å¯ä»£ç æ¢è¡Œ
wrap = false
# æ˜¯å¦æ˜¾ç¤ºä»£ç å—æ ‡é¢˜
header = true
#  è¡¨æ ¼é…ç½®
[params.page.table]
# æ˜¯å¦å¼€å¯è¡¨æ ¼æ’åº
sort = true
#  KaTeX æ•°å­¦å…¬å¼
[params.page.math]
enable = true
# é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$ å’Œ \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX æ’ä»¶ copy_tex
copyTex = true
# KaTeX æ’ä»¶ mhchem
mhchem = true
# ä½¿ç”¨ MathJax æ›¿ä»£ KaTeX
mathjax = false
#  Mapbox GL JS é…ç½®
[params.page.mapbox]
# Mapbox GL JS çš„ access token
accessToken = ""
# æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
lightStyle = "mapbox://styles/mapbox/light-v9"
# æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
darkStyle = "mapbox://styles/mapbox/dark-v9"
# æ˜¯å¦æ·»åŠ  NavigationControl
navigation = true
# æ˜¯å¦æ·»åŠ  GeolocateControl
geolocate = true
# æ˜¯å¦æ·»åŠ  ScaleControl
scale = true
# æ˜¯å¦æ·»åŠ  FullscreenControl
fullscreen = true
#  æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
[params.page.share]
enable = false
Twitter = true
Facebook = true
Linkedin = false
Whatsapp = true
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = false
VK = false
Buffer = false
Xing = false
Line = true
Instapaper = false
Pocket = false
Digg = false
Stumbleupon = false
Flipboard = false
Weibo = true
Renren = false
Myspace = true
Blogger = true
Baidu = false
Odnoklassniki = false
Evernote = true
Skype = false
Trello = false
Mix = false
Mastodon = false
# PlantUML åœ¨çº¿æ¸²æŸ“æœåŠ¡å™¨
[params.page.plantuml]
server = "https://www.plantuml.com/plantuml"

# instant.page è®¾ç½®
[params.page.instantpage]
enable = false

#  è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment]
enable = true
# Disqus è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.disqus]
#
enable = false
# Disqus çš„ shortname, ç”¨æ¥åœ¨æ–‡ç« ä¸­å¯ç”¨ Disqus è¯„è®ºç³»ç»Ÿ
shortname = ""
# Gitalk è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.gitalk]
#
enable = false
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# Valine è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.valine]
enable = false
appId = ""
appKey = ""
placeholder = ""
avatar = "mp"
meta = ""
pageSize = 10
lang = ""
visitor = true
recordIP = true
highlight = true
enableQQ = false
serverURLs = ""
#  emoji æ•°æ®æ–‡ä»¶åç§°ï¼Œé»˜è®¤æ˜¯ "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# ä½äº "themes/DoIt/assets/data/emoji/" ç›®å½•
# å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶ï¼š
# "assets/data/emoji/"
emoji = ""
# Waline è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.waline]
enable = true
serverURL = "https://comment.zzkrix.com"
pageview = true
comment = true
# emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
# meta = ['nick', 'mail', 'link']
# requiredMeta = []
# login = 'enable'
# wordLimit = 0
# pageSize = 10
# imageUploader = false
# highlighter = false
# texRenderer = false
# Facebook è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.facebook]
enable = false
width = "100%"
numPosts = 10
appId = ""
languageCode = "zh_CN"
#  Telegram Comments è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.telegram]
enable = false
siteID = ""
limit = 5
height = ""
color = ""
colorful = true
dislikes = false
outlined = false
dark = false
#  Commento è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.commento]
enable = false
#  Utterances è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.utterances]
enable = false
# owner/repo
repo = ""
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"
#  Twikoo è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.twikoo]
enable = false
envId = ""
region = ""
path = ""
cloudbase = true    # boolean : true / false. # æ˜¯å¦éƒ¨ç½²åœ¨è…¾è®¯äº‘ CloudBase
visitor = true
commentCount = true
#  Vssue è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.vssue]
enable = false
platform = ""     # ("bitbucket", "gitea", "gitee", "github", "gitlab")
owner = ""
repo = ""
clientId = ""
clientSecret = ""
#  Remark42 è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.remark42]
enable = false
host = ""
site_id = ""
max_shown_comments = 15
show_email_subscription = true
simple_view = false
#  giscus è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.giscus]
enable = false
# owner/repo
dataRepo = ""
dataRepoId = ""
dataCategory = ""
dataCategoryId = ""
dataMapping = "pathname"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "bottom"
lightTheme = "light"
darkTheme = "dark"
dataLang = "zh-CN"
dataLoading = "lazy"
# artalk è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.artalk]
enable = false
server = ""
site = ""
lite = false
katex = false
lightbox = false
pageview = true
commentCount = true
#  ç¬¬ä¸‰æ–¹åº“é…ç½®
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
#  æ›´å¤šç¬¬ä¸‰æ–¹åº“é…ç½®
# [params.page.library.css.someOtherCSS]
#   src = "someOther.css"
#   defer = true
#   attr = "customAttribute"
# ä½äº "assets/"
# æˆ–è€…
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavaScript = "some.js"
#  æ›´å¤šç¬¬ä¸‰æ–¹åº“é…ç½®
# [params.page.library.js.someOtherJavaScript]
#   src = "someOther.js"
#   defer = false
#   async = true
#   attr = "customAttribute"
# ä½äº "assets/"
# æˆ–è€…
# someJavaScript = "https://cdn.example.com/some.js"
#  é¡µé¢ SEO é…ç½®
[params.page.seo]
# å›¾ç‰‡ URL
images = []
# å‡ºç‰ˆè€…ä¿¡æ¯
[params.page.seo.publisher]
name = ""
logoUrl = ""
#  ç›¸å…³æ–‡ç« æ¨èé…ç½®
[params.page.related]
enable = false
count = 5


#  èµèµé…ç½®
[params.sponsor]
enable = true
bio = "å¦‚æœä½ è§‰å¾—è¿™ç¯‡æ–‡ç« å¯¹ä½ æœ‰æ‰€å¸®åŠ©ï¼Œæ¬¢è¿èµèµ~"
link = "https://raw.githubusercontent.com/zzkrix/blog-images/main/assets/zs-mini.jpg" # ä½ çš„èµèµé¡µé¢çš„åœ°å€
custom = ""                                                                           # è‡ªå®šä¹‰ HTML

#  TypeIt é…ç½®
[params.typeit]
# æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ ï¼ˆå•ä½æ˜¯æ¯«ç§’ï¼‰
speed = 100
# å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ ï¼ˆå•ä½æ˜¯æ¯«ç§’ï¼‰
cursorSpeed = 1000
# å…‰æ ‡çš„å­—ç¬¦ ï¼ˆæ”¯æŒ HTML æ ¼å¼ï¼‰
cursorChar = "|"
# æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ ï¼ˆå•ä½æ˜¯æ¯«ç§’ï¼Œ"-1" ä»£è¡¨æ— é™å¤§ï¼‰
duration = -1

# ç½‘ç«™éªŒè¯ä»£ç ï¼Œç”¨äº Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""
so = ""        # 360 search
sogou = ""

#  ç½‘ç«™ SEO é…ç½®
[params.seo]
# å›¾ç‰‡ URL
image = ""
# ç¼©ç•¥å›¾ URL
thumbnailUrl = ""
#
# Google æœç´¢ç»“æœä¸­ç½‘ç«™å¤‡ç”¨åå­—
alternateName = ["Hugo DoIt"]

#  ç½‘ç«™åˆ†æé…ç½®
[params.analytics]
enable = false
# Google Analytics
[params.analytics.google]
id = ""
# æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# è‡ªè¡Œæ‰˜ç®¡è¿½è¸ªå™¨æ—¶çš„ä¸»æœºè·¯å¾„
server = ""
#  Baidu Analytics
[params.analytics.baidu]
id = ""
#  Umami Analytics
[params.analytics.umami]
data_website_id = ""
src = ""
data_host_url = ""
data_domains = ""
#  Plausible Analytics
[params.analytics.plausible]
data_domain = ""
src = ""
#  Cloudflare Analytics
[params.analytics.cloudflare]
token = ""

#  Cookie è®¸å¯é…ç½®
[params.cookieconsent]
enable = false
# ç”¨äº Cookie è®¸å¯æ¨ªå¹…çš„æ–‡æœ¬å­—ç¬¦ä¸²
[params.cookieconsent.content]
message = ""
dismiss = ""
link = ""

#  ç¬¬ä¸‰æ–¹åº“æ–‡ä»¶çš„ CDN è®¾ç½®
[params.cdn]
# CDN æ•°æ®æ–‡ä»¶åç§°ï¼Œé»˜è®¤ä¸å¯ç”¨
# ("jsdelivr.yml")
# ä½äº "themes/DoIt/assets/data/cdn/" ç›®å½•
# å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶ï¼š
# "assets/data/cdn/"
data = ""

#  å…¼å®¹æ€§è®¾ç½®
[params.compatibility]
# æ˜¯å¦ä½¿ç”¨ Polyfill.io æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
polyfill = false

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
# è¯­æ³•é«˜äº®è®¾ç½®
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false æ˜¯å¿…è¦çš„è®¾ç½®
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
# Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
unsafe = true
# ç›®å½•è®¾ç½®
[markup.tableOfContents]
startLevel = 2
endLevel = 6

# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks é…ç½®
[Permalinks]
# posts = ":year/:month/:contentbasename"
posts = ":contentbasename"

# éšç§ä¿¡æ¯é…ç½®
[privacy]
#  Google Analytics ç›¸å…³éšç§ ï¼ˆè¢« params.analytics.google æ›¿ä»£ï¼‰
[privacy.googleAnalytics]
# ...
[privacy.x]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
#
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

# ç”¨äºåˆ†ç±»çš„è®¾ç½®
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"
